config/routes.rb
NasprRu2::Application.routes.draw do

  devise_for :users, :controllers => { :sessions => "users/sessions", :passwords => "users/passwords" }

  resources :posts
  resources :comments
  resource :contacts
  resource :page

  root :to => "home#index"

  resource :profile

  match '/auth/:provider/callback' => 'authentications#create'
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at DESC'

  scope :vote_true, :conditions => {:vote => true}
  scope :vote_false, :conditions => {:vote => false}

  validates_presence_of :comment
  validates_inclusion_of :vote, :in => [true, false]

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

  # Будет браться дефолтный аватар для пользователя или сам аватар пользователя
  # если имеется
  def user_avatar
    "avatar2.jpg"
  end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :sender, :contact_type, :body
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

  after_create :send_contact_form

  TYPE_CONTACT = [[I18n.t("select.questions"), "questions"], [I18n.t("select.error"), "error"], [I18n.t("select.improving"), "improving"], [I18n.t("select.advertising"), "advertising"]]

  def send_contact_form
    Notifer.send_contact_form(self).deliver
  end
end

app/models/content.rb
class Content < ActiveRecord::Base

  validates_presence_of :body, :name

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base

  order :created_at
  belongs_to :user
  attr_accessor :rule

  scope :main_page, :limit => 10, :order => "created_at DESC"
  acts_as_commentable

  validates_presence_of :subject, :body, :user_id
  validates_inclusion_of :rule, :in => ["1"]

end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_authorization_role
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_authorization_subject  :association_name => :roles

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :posts

  after_save :set_role

  def set_role
    self.has_role!("user")
  end

  def avatar?
    false
  end

  # Будет браться дефолтный аватар для пользователя или сам аватар пользователя
  # если имеется
  def user_avatar
    "avatar2.jpg"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from 'Acl9::AccessDenied', :with => :access_denied
  rescue_from 'ActiveRecord::RecordNotFound', :with => :render_404

  protect_from_forgery

  def resource 
    nil
  end

  def access_denied
    if current_user
      render :template => 'home/access_denied'
    else
      flash[:notice] = t("rescue_from.acl9")
      redirect_to new_user_session_url
    end
  end

  def render_404
    render :template => "error_pages/404.html", :status => "404 Not Found", :layout => false
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter "check_captcha", :only => :create

  def create
    @post = Post.find(params[:comment][:commentable_id])
    current_user ? additional_hash = {:user_id => current_user.id} : additional_hash = {}
    @comment = @post.comments.create(params[:comment].merge(additional_hash))
    if @comment.save
      redirect_to @post, :notice => t("notice.comment_create")
    else
      @comments = @post.comments.recent
      @true_comments = @post.comments.vote_true
      @false_comments = @post.comments.vote_false
      render :file => "/posts/show.haml"
    end
  end

  private

  def check_captcha
    unless current_user
      if Rails.env.to_s == "production" || Rails.env.to_s == "development"
        redirect_to :back, :notice => t("notice.captcha") if verify_recaptcha == true
      end
    end
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    if @contact.save
      redirect_to new_contacts_path, :notice => I18n.t("notice.contact_save")
    else
      render :action => "new"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @comment = Post.last.comments.new(:vote => true) unless Post.all.blank?
    @posts = Post.main_page
    @last_post = @posts.first unless @posts.blank?
    @comments = @last_post.comments unless @last_post.blank?
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show 
    @page = Page.find_by_permalink(params[:permalink])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  access_control do
    actions :index, :show do
      allow all
    end

    actions :create, :new do 
      allow :user
    end
  end

  before_filter :content_rules, :only => [:new, :create]

  def index
    @posts = if params[:type]
      User.find_by_email(params[:type]).posts.paginate(:page => params[:page], :per_page => 10, :order => "created_at DESC")
    else
      Post.all.paginate(:page => params[:page], :per_page => 10, :order => "created_at DESC")
    end
  end

  def show
    @post = Post.find(params[:id])

    @true_comments = @post.comments.vote_true
    @num_true_comments = @post.comments.vote_true.size

    @false_comments = @post.comments.vote_false
    @num_false_comments = @post.comments.vote_false.size

    @comment = @post.comments.new(:vote => true)
  end

  def create
    @post = current_user.posts.new(params[:post])
    if @post.save
      flash[:notice] = t("notice.post_create") 
      redirect_to root_path
    else
      render :action => :new
    end
  end

  def new 
    @post = Post.new
  end

  private

  def content_rules
    @content_rules = Content.find_by_name("rules")
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def class_for_element_menu(name)
    if params[:controller] == "home" && name == t("link.main_page")
      "active"
    elsif params[:controller] == "profiles" && name == t("link.profile")
      "active"
    elsif params[:controller] == "posts" && !params[:type].blank? && name == t("link.my_posts")
      "active"
    elsif params[:controller] == "posts" && (params[:action] == "new" || params[:action] == "create") && name == t("link.create_post")
      "active"
    else
      "no_active"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper

  def human_vote comment
    comment.vote == true ? t("view.home.for") : t("view.home.against")
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!(header = true)
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    unless header == false
      sentence = I18n.t("errors.messages.not_saved", :count => resource.errors.count, :resource => resource_name)
    end

    html_part_1 = <<-HTML
    <div id="error_explanation">
    HTML

    # Можно без заголовка
    if header == true
      html_part_2 = <<-HTML
        <h2>#{sentence}</h2>
      HTML
    end

    html_part_3 = <<-HTML
      <ul>#{messages}</ul>
    </div>
    HTML

    html = html_part_1
    html += html_part_2 if html_part_2
    html += html_part_3

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/_block_dish.haml
%div
  = block_dish.name

app/views/home/index.haml
%table.main_table
  %tbody
    %tr
      %td.valign
        %section
        %h1.header_h1 
          = t("h1.last_post")
        %table.list_lastdebate
          %tbody
            - @posts.each do |post|
              %tr
                %td{:colspan => "2"}
                  = link_to post.subject, post_path(post)
                  (
                  %span.trueansver> 1072
                  |
                  %span.falseansver> 5202
                  )
            %tr
              %td.hightred
                - if current_user
                  = link_to t("link.new_post"), new_post_path
                - else
                  = link_to t("link.new_post"), new_user_session_path, :class => "show_login_form"
              %td.hightblue
                = link_to t("link.posts"), posts_path


      %td.valign
        - if @last_post
          %section
          %h1.header_h1 Последние спор
          %h2
            = link_to @last_post.subject, post_url(@last_post), :class => "color_h2_a"
          %div
            - if @last_post.user.nil? && !@last_post.user.avatar?
              .avatar
                = image_tag @last_post.user.avatar.url, :alt => t("link.avatar")
            .text
              = @last_post.body
          .clear
          %div
            .ansvertruenum
              %span.za
                = t("view.home.support")
              %span.numvoited
                = @last_post.comments.vote_true.size
            .ansverfalsenum
              %span.protiv
                = t("view.home.not_support")
              %span.numvoited 
                = @last_post.comments.vote_false.size
          .clear
          .golosovat2
            .dot_link
              = link_to t("link.voit"), "#", :id => "voit_link"
          - if @comment
            .voited_form{:style => "display:none;"}
              = form_for @comment do |f|
                = f.hidden_field :commentable_id
                %table
                  %tr
                    %td
                      = f.radio_button :vote, "true"
                      %span.zasmall
                        = t("view.home.supporting")
                    %td{:class => "text_align_right"}
                      %span.protivsmall 
                        = t("view.home.against")
                      = f.radio_button :vote, "false"
                  %tr
                    %td{:colspan => 2}
                      %br/
                      = t("view.home.ansver")
                      = f.text_area :comment
                      %br/
                  - unless current_user
                    %tr 
                      %td{:colspan => 2}
                        = recaptcha_tags
                  %tr 
                    %td{:colspan => 2}
                      = f.submit t("button.post")
          - if @comments
            - @comments.each do |comment|
              .ansver
                .avataranver
                  - if comment.user && comment.user.avatar?
                    %div
                      = image_tag comment.user.avatar.url, :alt => t("link.alt")
                  .rezansverfalse
                    = human_vote(comment)
                .text
                  = h comment.comment
              .clear
:javascript 
  $(document).ready(function() {
    open_comment()
  });

app/views/home/show.haml
%h1
  Добро пожаловать

%table{:border => 1}
  %tr
    %td
      Subject
    %td
      Created at
    %td
      Number comments
    - @posts.each do |post|
      %tr
        %td
          = link_to post.subject, post_url(post)
        %td
          = post.created_at
        %td
          = post.comments.size