config/routes.rb
NasprRu2::Application.routes.draw do

  devise_for :users, :controllers => { :sessions => "users/sessions", :passwords => "users/passwords" }

  resources :posts
  resources :comments
  resource :contacts
  resource :page

  root :to => "home#index"

  resource :profile

  match '/auth/:provider/callback' => 'authentications#create'
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at DESC'

  scope :vote_true, :conditions => {:vote => true}
  scope :vote_false, :conditions => {:vote => false}

  validates_presence_of :comment
  validates_inclusion_of :vote, :in => [true, false]

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

  # Будет браться дефолтный аватар для пользователя или сам аватар пользователя
  # если имеется
  def user_avatar
    "avatar2.jpg"
  end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :sender, :contact_type, :body
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

  after_create :send_contact_form

  TYPE_CONTACT = [[I18n.t("select.questions"), "questions"], [I18n.t("select.error"), "error"], [I18n.t("select.improving"), "improving"], [I18n.t("select.advertising"), "advertising"]]

  def send_contact_form
    Notifer.send_contact_form(self).deliver
  end
end

app/models/content.rb
class Content < ActiveRecord::Base

  validates_presence_of :body, :name

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base

  order :created_at
  belongs_to :user
  attr_accessor :rule

  scope :main_page, :limit => 10, :order => "created_at DESC"
  acts_as_commentable

  validates_presence_of :subject, :body, :user_id
  validates_inclusion_of :rule, :in => ["1"]

end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_authorization_role
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_authorization_subject  :association_name => :roles

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :posts

  after_save :set_role

  def set_role
    self.has_role!("user")
  end

  def avatar?
    false
  end

  # Будет браться дефолтный аватар для пользователя или сам аватар пользователя
  # если имеется
  def user_avatar
    "avatar2.jpg"
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter "check_captcha", :only => :create

  def create
    @post = Post.find(params[:comment][:commentable_id])
    current_user ? additional_hash = {:user_id => current_user.id} : additional_hash = {}
    @comment = @post.comments.create(params[:comment].merge(additional_hash))
    if @comment.save
      redirect_to @post, :notice => t("notice.comment_create")
    else
      @comments = @post.comments.recent
      @true_comments = @post.comments.vote_true
      @false_comments = @post.comments.vote_false
      render :file => "/posts/show.haml"
    end
  end

  private

  def check_captcha
    unless current_user
      if Rails.env.to_s == "production" || Rails.env.to_s == "development"
        redirect_to :back, :notice => t("notice.captcha") if verify_recaptcha == true
      end
    end
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    if @contact.save
      redirect_to new_contacts_path, :notice => I18n.t("notice.contact_save")
    else
      render :action => "new"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @comment = Post.last.comments.new(:vote => true) unless Post.all.blank?
    @posts = Post.main_page
    @last_post = @posts.first unless @posts.blank?
    @comments = @last_post.comments unless @last_post.blank?
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show 
    @page = Page.find_by_permalink(params[:permalink])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  access_control do
    actions :index, :show do
      allow all
    end

    actions :create, :new do 
      allow :user
    end
  end

  before_filter :content_rules, :only => [:new, :create]

  def index
    @posts = if params[:type]
      User.find_by_email(params[:type]).posts.paginate(:page => params[:page], :per_page => 10, :order => "created_at DESC")
    else
      Post.all.paginate(:page => params[:page], :per_page => 10, :order => "created_at DESC")
    end
  end

  def show
    @post = Post.find(params[:id])

    @true_comments = @post.comments.vote_true
    @num_true_comments = @post.comments.vote_true.size

    @false_comments = @post.comments.vote_false
    @num_false_comments = @post.comments.vote_false.size

    @comment = @post.comments.new(:vote => true)
  end

  def create
    @post = current_user.posts.new(params[:post])
    if @post.save
      flash[:notice] = t("notice.post_create") 
      redirect_to root_path
    else
      render :action => :new
    end
  end

  def new 
    @post = Post.new
  end

  private

  def content_rules
    @content_rules = Content.find_by_name("rules")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def class_for_element_menu(name)
    if params[:controller] == "home" && name == t("link.main_page")
      "active"
    elsif params[:controller] == "profiles" && name == t("link.profile")
      "active"
    elsif params[:controller] == "posts" && !params[:type].blank? && name == t("link.my_posts")
      "active"
    elsif params[:controller] == "posts" && (params[:action] == "new" || params[:action] == "create") && name == t("link.create_post")
      "active"
    else
      "no_active"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper

  def human_vote comment
    comment.vote == true ? t("view.home.for") : t("view.home.against")
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!(header = true)
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    unless header == false
      sentence = I18n.t("errors.messages.not_saved", :count => resource.errors.count, :resource => resource_name)
    end

    html_part_1 = <<-HTML
    <div id="error_explanation">
    HTML

    # Можно без заголовка
    if header == true
      html_part_2 = <<-HTML
        <h2>#{sentence}</h2>
      HTML
    end

    html_part_3 = <<-HTML
      <ul>#{messages}</ul>
    </div>
    HTML

    html = html_part_1
    html += html_part_2 if html_part_2
    html += html_part_3

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title naspr.ru
    = stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/red/style", "web-app-theme/override", :cache => true
    = javascript_include_tag :defaults, :cache => true
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          %a{:href => "/"} naspr.ru
        #user-navigation
          %ul.wat-cf
            %li
              %a{:href => "#"}= t("web-app-theme.profile", :default => "Profile")
            %li
              %a{:href => "#"}= t("web-app-theme.settings", :default => "Settings")
            %li
              %a.logout{:href => "/logout"}= t("web-app-theme.logout", :default => "Logout")
        #main-navigation
          %ul.wat-cf
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
        #main
          = yield
          #footer
            .block
              %p
                Copyright &copy; #{Time.now.year} naspr.ru.
        #sidebar
          = yield :sidebar

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "Общественное мнение, истина, прав ли я, споры, мнения, дебаты, мнение народа, коллективные споры", :name => "keywords"}/
    %meta{:content => "Общественное мнение, истина, прав ли я, споры, мнения, дебаты, мнение народа, коллективные споры", :name => "description"}/
    = stylesheet_link_tag("main.css")
    %title Общественное мнение, истина, прав ли я, споры, мнения, дебаты, мнение народа, коллективные споры
    = javascript_include_tag "jquery.min.js"
    = javascript_include_tag "modernizr-1.7.min.js"
    = javascript_include_tag "jquery-ui-1.8.12.custom.min.js"
    = javascript_include_tag "rails.js"
    = javascript_include_tag "application.js"
    = csrf_meta_tag
  %body
    - unless current_user
      .registration_box
        .close_login_box
        .login_box.boxshadow
    %header
      .logo
        %h1
          %a{:href => "http://naspr.ru/"}
            = image_tag "naspr.jpg", :alt => t("alt.opinion_people")
      .header
        %h1= t("h1.whether_rights_i")
      - unless current_user
        .enter
          = link_to t("view.main_menu.sign_in"), new_user_session_path, :class => "show_login_form"
        .registration
          = link_to t("view.main_menu.registration"), new_user_registration_path
      - else
        .registration
          = link_to t("view.main_menu.logout"), destroy_user_session_path
    = render :partial => "shared/main_menu"
    = render :partial => "shared/flashes"
    .content
      = yield
    %footer
      .footer_menu
        = link_to t("link.advertising"), page_url(:permalink => "advertisement")
        = link_to t("link.contacts"), new_contacts_path
      .clear

:javascript
  $(document).ready(function() {
    fix_navigation()
  })

app/views/layouts/sign.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web App</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override", :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="box">
      <%= yield %>            
    </div>
  </div>
</body>
</html>

app/views/notifer/send_contact_form.haml
%p
  %label
    = t("labels.type")
  = @contact_form.contact_type
%p
  %label
    = t("labels.sender")
  = @contact_form.sender
%p
  %label
    = t("labels.email")
  = @contact_form.email
%p
  %label
    = t("labels.body")
  = @contact_form.body

app/views/pages/show.haml
%h1{:class => "header_h1"}
  = @page.subject
= @page.body

app/views/shared/_flashes.haml
.flash
  - if notice || flash[:notice]
    .message.notice
      %p
        = notice
  - if alert || flash[:error]
    .message.error
      %p
        = alert

app/views/shared/_links.haml
- if controller_name != 'sessions'
  #div_sign_in
    = link_to t("link.sign_in"), new_session_path(resource_name), :class => "ajax_sign_in"
- if devise_mapping.registerable? && controller_name != 'registrations'
  #div_sign_up.valign_right
    = link_to t("link.sign_up"), new_registration_path(resource_name)
- if devise_mapping.recoverable? && controller_name != 'passwords'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/shared/_main_menu.haml
%nav
  .nav
    #line
    - link_to root_path, :class => class_for_element_menu(t("link.main_page")) do 
      .element_menu
        .top_part
          .left_part
          .middle_part
            = t("link.main_page")
          .right_part
          .clear
        .bottom_part
          .bottom_left_part
          .bottom_middle_part
          .bottom_right_part

  - if current_user
    - link_to root_path, :class => class_for_element_menu(t("link.profile")) do 
      .element_menu
        .top_part
          .left_part
          .middle_part
            = t("link.profile")
          .right_part
          .clear
        .bottom_part
          .bottom_left_part
          .bottom_middle_part
          .bottom_right_part

      - link_to posts_path(:type => current_user.email), :class => class_for_element_menu(t("link.my_posts")) do 
        .element_menu
          .top_part
            .left_part
            .middle_part
              = t("link.my_posts")
            .right_part
            .clear
          .bottom_part
            .bottom_left_part
            .bottom_middle_part
            .bottom_right_part

      - link_to new_post_path, :class => class_for_element_menu(t("link.create_post")) do 
        .element_menu
          .top_part
            .left_part
            .middle_part
              = t("link.create_post")
            .right_part
            .clear
          .bottom_part
            .bottom_left_part
            .bottom_middle_part
            .bottom_right_part